[project]
name = "lionsfin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "duckdb>=1.3.2",
    "pandas>=2.3.1",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.12.2",
]
